### ISSUE TITLE
something

### ISSUE THREAD

**Issue by kenbunji** [kenbunji/estat#1]

**Comment by OneProgrammerKokubunji** [comment]
estat.py
                for f in self.cmd_line(
                    self.build_cmd(
                        ['ls', self.path['tmp'] + '.'.join([self._['appId'], statsDataId, '*', 'json'])])
                ).decode().split('\n')
                if f != ''

API.py

from __future__ import unicode_literals
from builtins import bytes
from builtins import dict



            ix.sort()
            ix = [list(hash.values())[0] for hash in ix]
            for i, json_file in enumerate(ix):


            for body in dat['body']:
                newCSV.append(list(body.values()))
            for i, x in enumerate(newCSV):
